import type { Metadata } from "next";
import "./globals.css"
import Link from "next/link";

export const metadata: Metadata = {
  title: "Practicing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-[100vh] flex flex-col">
        <header className="h-[60px] flex justify-between px-10 bg-cyan-800 items-center text-white">
          <h1 className="text-2xl font-extrabold">
            Roasts
          </h1>
          <nav>
            <ul className="flex gap-5 text-xl font-bold">
              <li><Link href="/" className="hover:underline">Home</Link></li>
              <li><Link href="/jokes" className="hover:underline">Jokes</Link></li>
            </ul>
          </nav>
        </header>
        <main className="flex-1 bg-cyan-100">{children}</main>
      </body>
    </html>
  );
}
